# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-18 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_auto_20190718_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AlterField(
            model_name='authors',
            name='books',
            field=models.ManyToManyField(related_name='author', to='books_authors_app.Book'),
        ),
    ]
